using System.Text;
using SchemaForge.Core.Models;
using SchemaForge.Core.Services;

namespace SchemaForge.Core.DdlGeneration;

public class PostgresDdlGenerator : IDdlGeneratorService
{
    public SqlDialect Dialect => SqlDialect.PostgreSQL;

    private static string QuoteId(string name) => $"\"{name.Replace("\"", "\"\"")}\"";


    public string GenerateFullDdl(SchemaDocument schema)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- Generated by SchemaForge");
        sb.AppendLine($"-- Dialect: PostgreSQL");
        sb.AppendLine($"-- Generated at: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine();

        // Topological sort for FK dependency order
        var sorted = TopologicalSort(schema);

        // 1. CREATE TABLEs
        foreach (var table in sorted)
        {
            sb.AppendLine(GenerateCreateTable(table, schema));
            sb.AppendLine();
        }

        // 2. ALTER TABLE ADD CONSTRAINTs (foreign keys)
        foreach (var table in sorted)
        {
            var fkStatements = GenerateForeignKeyConstraints(table, schema);
            if (fkStatements.Length > 0)
            {
                sb.AppendLine(fkStatements);
                sb.AppendLine();
            }
        }

        // 3. CREATE INDEXes
        foreach (var table in sorted)
        {
            foreach (var index in table.Indexes)
            {
                sb.AppendLine(GenerateCreateIndex(index, table));
            }
        }

        // 4. COMMENTs
        var comments = GenerateComments(sorted);
        if (comments.Length > 0)
        {
            sb.AppendLine();
            sb.Append(comments);
        }

        return sb.ToString().TrimEnd();
    }

    public string GenerateCreateTable(TableDefinition table, SchemaDocument schema)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"CREATE TABLE {QuoteId(table.Name)} (");

        var lines = new List<string>();

        foreach (var col in table.Columns)
        {
            lines.Add($"  {GenerateColumnDef(col)}");
        }

        // Composite primary key
        var pkColumns = table.Columns.Where(c => c.IsPrimaryKey).ToList();
        if (pkColumns.Count > 1)
        {
            var pkNames = string.Join(", ", pkColumns.Select(c => QuoteId(c.Name)));
            lines.Add($"  PRIMARY KEY ({pkNames})");
        }

        // Check constraints
        foreach (var check in table.CheckConstraints)
        {
            var name = string.IsNullOrEmpty(check.Name) ? "" : $"CONSTRAINT {QuoteId(check.Name)} ";
            lines.Add($"  {name}CHECK ({check.Expression})");
        }

        sb.AppendLine(string.Join(",\n", lines));
        sb.Append(");");

        return sb.ToString();
    }

    public string GenerateCreateIndex(IndexDefinition index, TableDefinition table)
    {
        var unique = index.IsUnique ? "UNIQUE " : "";
        var columns = index.ColumnIds
            .Select(id => table.Columns.FirstOrDefault(c => c.Id == id))
            .Where(c => c != null)
            .Select(c => QuoteId(c!.Name));

        var sql = $"CREATE {unique}INDEX {QuoteId(index.Name)} ON {QuoteId(table.Name)} ({string.Join(", ", columns)})";

        if (!string.IsNullOrEmpty(index.WhereClause))
            sql += $" WHERE {index.WhereClause}";

        return sql + ";";
    }

    public string GenerateDropTable(string tableName) =>
        $"DROP TABLE IF EXISTS {QuoteId(tableName)} CASCADE;";

    private string GenerateForeignKeyConstraints(TableDefinition table, SchemaDocument schema)
    {
        var sb = new StringBuilder();
        var relationships = schema.Relationships
            .Where(r => r.SourceTableId == table.Id)
            .ToList();

        foreach (var rel in relationships)
        {
            var sourceCol = table.Columns.FirstOrDefault(c => c.Id == rel.SourceColumnId);
            var targetTable = schema.Tables.FirstOrDefault(t => t.Id == rel.TargetTableId);
            var targetCol = targetTable?.Columns.FirstOrDefault(c => c.Id == rel.TargetColumnId);

            if (sourceCol == null || targetTable == null || targetCol == null)
                continue;

            var constraintName = !string.IsNullOrEmpty(rel.Name)
                ? rel.Name
                : $"fk_{table.Name}_{sourceCol.Name}";

            var stmt = $"ALTER TABLE {QuoteId(table.Name)} ADD CONSTRAINT {QuoteId(constraintName)} " +
                       $"FOREIGN KEY ({QuoteId(sourceCol.Name)}) REFERENCES {QuoteId(targetTable.Name)} ({QuoteId(targetCol.Name)})";

            if (rel.OnDelete != ReferentialAction.NoAction)
                stmt += $" ON DELETE {FormatReferentialAction(rel.OnDelete)}";
            if (rel.OnUpdate != ReferentialAction.NoAction)
                stmt += $" ON UPDATE {FormatReferentialAction(rel.OnUpdate)}";

            sb.AppendLine(stmt + ";");
        }

        return sb.ToString().TrimEnd();
    }

    private static string GenerateComments(List<TableDefinition> tables)
    {
        var sb = new StringBuilder();

        foreach (var table in tables)
        {
            if (!string.IsNullOrEmpty(table.Comment))
            {
                sb.AppendLine($"COMMENT ON TABLE {QuoteId(table.Name)} IS '{EscapeSqlString(table.Comment)}';");
            }

            foreach (var col in table.Columns)
            {
                if (!string.IsNullOrEmpty(col.Comment))
                {
                    sb.AppendLine($"COMMENT ON COLUMN {QuoteId(table.Name)}.{QuoteId(col.Name)} IS '{EscapeSqlString(col.Comment)}';");
                }
            }
        }

        return sb.ToString().TrimEnd();
    }

    private string GenerateColumnDef(ColumnDefinition col)
    {
        var parts = new List<string>();

        if (col.IsPrimaryKey && col.IsAutoIncrement)
        {
            // Use GENERATED ALWAYS AS IDENTITY for auto-increment PKs
            parts.Add(QuoteId(col.Name));
            parts.Add(MapDataType(col));
            parts.Add("GENERATED ALWAYS AS IDENTITY");
            parts.Add("PRIMARY KEY");
        }
        else
        {
            parts.Add(QuoteId(col.Name));
            parts.Add(MapDataType(col));

            if (col.IsPrimaryKey)
            {
                // Only add inline PK for single-column PKs (composite handled at table level)
                parts.Add("PRIMARY KEY");
            }
        }

        if (!col.IsNullable && !col.IsPrimaryKey)
            parts.Add("NOT NULL");

        if (col.IsUnique)
            parts.Add("UNIQUE");

        if (col.DefaultValue != null)
            parts.Add($"DEFAULT {col.DefaultValue}");

        if (col.CheckExpression != null)
            parts.Add($"CHECK ({col.CheckExpression})");

        return string.Join(" ", parts);
    }

    private static string MapDataType(ColumnDefinition col) => col.DataType switch
    {
        LogicalDataType.Integer => "INTEGER",
        LogicalDataType.BigInteger => "BIGINT",
        LogicalDataType.SmallInteger => "SMALLINT",
        LogicalDataType.Decimal => col.Precision.HasValue && col.Scale.HasValue
            ? $"NUMERIC({col.Precision},{col.Scale})"
            : col.Precision.HasValue
                ? $"NUMERIC({col.Precision})"
                : "NUMERIC",
        LogicalDataType.Float => "DOUBLE PRECISION",
        LogicalDataType.Boolean => "BOOLEAN",
        LogicalDataType.Text => "TEXT",
        LogicalDataType.Varchar => col.Length.HasValue ? $"VARCHAR({col.Length})" : "TEXT",
        LogicalDataType.Char => col.Length.HasValue ? $"CHAR({col.Length})" : "TEXT",
        LogicalDataType.Date => "DATE",
        LogicalDataType.DateTime => "TIMESTAMP",
        LogicalDataType.Time => "TIME",
        LogicalDataType.Timestamp => "TIMESTAMPTZ",
        LogicalDataType.Blob => "BYTEA",
        LogicalDataType.Uuid => "UUID",
        LogicalDataType.Json => "JSONB",
        _ => "TEXT"
    };

    private static string FormatReferentialAction(ReferentialAction action) => action switch
    {
        ReferentialAction.Cascade => "CASCADE",
        ReferentialAction.SetNull => "SET NULL",
        ReferentialAction.Restrict => "RESTRICT",
        ReferentialAction.SetDefault => "SET DEFAULT",
        _ => "NO ACTION"
    };

    private static string EscapeSqlString(string value) =>
        value.Replace("'", "''");

    private static List<TableDefinition> TopologicalSort(SchemaDocument schema)
    {
        var tables = schema.Tables.ToDictionary(t => t.Id);
        var visited = new HashSet<string>();
        var result = new List<TableDefinition>();

        // Build dependency graph: table -> tables it references
        var deps = new Dictionary<string, HashSet<string>>();
        foreach (var table in schema.Tables)
            deps[table.Id] = [];

        foreach (var rel in schema.Relationships)
        {
            if (deps.ContainsKey(rel.SourceTableId) && tables.ContainsKey(rel.TargetTableId))
                deps[rel.SourceTableId].Add(rel.TargetTableId);
        }

        void Visit(string tableId)
        {
            if (visited.Contains(tableId)) return;
            visited.Add(tableId);

            foreach (var dep in deps[tableId])
                Visit(dep);

            if (tables.TryGetValue(tableId, out var table))
                result.Add(table);
        }

        foreach (var tableId in tables.Keys)
            Visit(tableId);

        return result;
    }
}
