using System.Text;
using SchemaForge.Core.Models;
using SchemaForge.Core.Services;

namespace SchemaForge.Core.DdlGeneration;

public class SqliteDdlGenerator : IDdlGeneratorService
{
    public SqlDialect Dialect => SqlDialect.SQLite;

    private static string QuoteId(string name) => $"\"{name.Replace("\"", "\"\"")}\"";


    public string GenerateFullDdl(SchemaDocument schema)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- Generated by SchemaForge");
        sb.AppendLine($"-- Dialect: SQLite");
        sb.AppendLine($"-- Generated at: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine();

        // Topological sort for FK dependency order
        var sorted = TopologicalSort(schema);

        foreach (var table in sorted)
        {
            sb.AppendLine(GenerateCreateTable(table, schema));
            sb.AppendLine();
        }

        foreach (var table in sorted)
        {
            foreach (var index in table.Indexes)
            {
                sb.AppendLine(GenerateCreateIndex(index, table));
            }
        }

        return sb.ToString().TrimEnd();
    }

    public string GenerateCreateTable(TableDefinition table, SchemaDocument schema)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"CREATE TABLE {QuoteId(table.Name)} (");

        var lines = new List<string>();

        foreach (var col in table.Columns)
        {
            lines.Add($"  {GenerateColumnDef(col)}");
        }

        // Composite primary key
        var pkColumns = table.Columns.Where(c => c.IsPrimaryKey).ToList();
        if (pkColumns.Count > 1)
        {
            var pkNames = string.Join(", ", pkColumns.Select(c => QuoteId(c.Name)));
            lines.Add($"  PRIMARY KEY ({pkNames})");
        }

        // Inline foreign keys (SQLite doesn't support ALTER TABLE ADD CONSTRAINT)
        var relationships = schema.Relationships
            .Where(r => r.SourceTableId == table.Id)
            .ToList();

        foreach (var rel in relationships)
        {
            var sourceCol = table.Columns.FirstOrDefault(c => c.Id == rel.SourceColumnId);
            var targetTable = schema.Tables.FirstOrDefault(t => t.Id == rel.TargetTableId);
            var targetCol = targetTable?.Columns.FirstOrDefault(c => c.Id == rel.TargetColumnId);

            if (sourceCol != null && targetTable != null && targetCol != null)
            {
                var fk = $"  FOREIGN KEY ({QuoteId(sourceCol.Name)}) REFERENCES {QuoteId(targetTable.Name)} ({QuoteId(targetCol.Name)})";
                if (rel.OnDelete != ReferentialAction.NoAction)
                    fk += $" ON DELETE {FormatReferentialAction(rel.OnDelete)}";
                if (rel.OnUpdate != ReferentialAction.NoAction)
                    fk += $" ON UPDATE {FormatReferentialAction(rel.OnUpdate)}";
                lines.Add(fk);
            }
        }

        // Check constraints
        foreach (var check in table.CheckConstraints)
        {
            var name = string.IsNullOrEmpty(check.Name) ? "" : $"CONSTRAINT {QuoteId(check.Name)} ";
            lines.Add($"  {name}CHECK ({check.Expression})");
        }

        sb.AppendLine(string.Join(",\n", lines));
        sb.Append(");");

        return sb.ToString();
    }

    public string GenerateCreateIndex(IndexDefinition index, TableDefinition table)
    {
        var unique = index.IsUnique ? "UNIQUE " : "";
        var columns = index.ColumnIds
            .Select(id => table.Columns.FirstOrDefault(c => c.Id == id))
            .Where(c => c != null)
            .Select(c => QuoteId(c!.Name));

        var sql = $"CREATE {unique}INDEX {QuoteId(index.Name)} ON {QuoteId(table.Name)} ({string.Join(", ", columns)})";

        if (!string.IsNullOrEmpty(index.WhereClause))
            sql += $" WHERE {index.WhereClause}";

        return sql + ";";
    }

    public string GenerateDropTable(string tableName) =>
        $"DROP TABLE IF EXISTS {QuoteId(tableName)};";

    private string GenerateColumnDef(ColumnDefinition col)
    {
        var parts = new List<string> { QuoteId(col.Name), MapDataType(col) };

        // Single-column PK with autoincrement
        if (col.IsPrimaryKey && col.IsAutoIncrement)
        {
            parts.Add("PRIMARY KEY AUTOINCREMENT");
        }
        else if (col.IsPrimaryKey)
        {
            // Only add inline PK for single-column PKs (handled at table level for composite)
            parts.Add("PRIMARY KEY");
        }

        if (!col.IsNullable && !col.IsPrimaryKey)
            parts.Add("NOT NULL");

        if (col.IsUnique)
            parts.Add("UNIQUE");

        if (col.DefaultValue != null)
            parts.Add($"DEFAULT {col.DefaultValue}");

        if (col.CheckExpression != null)
            parts.Add($"CHECK ({col.CheckExpression})");

        return string.Join(" ", parts);
    }

    private static string MapDataType(ColumnDefinition col) => col.DataType switch
    {
        LogicalDataType.Integer => "INTEGER",
        LogicalDataType.BigInteger => "INTEGER",
        LogicalDataType.SmallInteger => "INTEGER",
        LogicalDataType.Decimal => "REAL",
        LogicalDataType.Float => "REAL",
        LogicalDataType.Boolean => "INTEGER",
        LogicalDataType.Text => "TEXT",
        LogicalDataType.Varchar => col.Length.HasValue ? $"VARCHAR({col.Length})" : "TEXT",
        LogicalDataType.Char => col.Length.HasValue ? $"CHAR({col.Length})" : "TEXT",
        LogicalDataType.Date => "TEXT",
        LogicalDataType.DateTime => "TEXT",
        LogicalDataType.Time => "TEXT",
        LogicalDataType.Timestamp => "TEXT",
        LogicalDataType.Blob => "BLOB",
        LogicalDataType.Uuid => "TEXT",
        LogicalDataType.Json => "TEXT",
        _ => "TEXT"
    };

    private static string FormatReferentialAction(ReferentialAction action) => action switch
    {
        ReferentialAction.Cascade => "CASCADE",
        ReferentialAction.SetNull => "SET NULL",
        ReferentialAction.Restrict => "RESTRICT",
        ReferentialAction.SetDefault => "SET DEFAULT",
        _ => "NO ACTION"
    };

    private static List<TableDefinition> TopologicalSort(SchemaDocument schema)
    {
        var tables = schema.Tables.ToDictionary(t => t.Id);
        var visited = new HashSet<string>();
        var result = new List<TableDefinition>();

        // Build dependency graph: table -> tables it references
        var deps = new Dictionary<string, HashSet<string>>();
        foreach (var table in schema.Tables)
            deps[table.Id] = [];

        foreach (var rel in schema.Relationships)
        {
            if (deps.ContainsKey(rel.SourceTableId) && tables.ContainsKey(rel.TargetTableId))
                deps[rel.SourceTableId].Add(rel.TargetTableId);
        }

        void Visit(string tableId)
        {
            if (visited.Contains(tableId)) return;
            visited.Add(tableId);

            foreach (var dep in deps[tableId])
                Visit(dep);

            if (tables.TryGetValue(tableId, out var table))
                result.Add(table);
        }

        foreach (var tableId in tables.Keys)
            Visit(tableId);

        return result;
    }
}
